node{
    stage('Checkout Stage') {
        git url: 'https://github.com/giokavlashvili/WebApplication1.git', branch: 'master'
    }
    stage("clean"){
        bat "dotnet clean"
    }
    stage("restore"){
        bat "dotnet restore"
    }
    stage("build"){
        bat "dotnet build --configuration Release"
    }
    stage("publish"){
        bat "dotnet publish -c Release"
    }
    stage("capture"){
        archiveArtifacts artifacts: '**/bin/Release/net7.0/**'
    }
    stage("deploy"){
        bat '"C:\\Program Files\\IIS\\Microsoft Web Deploy V3\\msdeploy.exe" -verb:sync -source:contentPath=C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\pipe\\WebApplication1\\bin\\Release\\net7.0\\publish -dest:contentPath=C:\\inetpub\\wwwroot\\TestWebApp'
    }
}