node{
    stage("build"){
        bat "dotnet build --configuration Release"
    }
    stage("publish"){
        bat "dotnet publish --runtime osx.10.11-x64"
    }
    stage("capture"){
        archiveArtifacts artifacts: '**/Release/net7.0/**'
    }
    stage("deploy"){
        bat "Xcopy \\WebApplication1\\bin\\Release\\net7.0\\ c:\\inetpub\\wwwroot\\TestWebApp /E /H /C /I."
    }
}